ports:
- port: 8080
# ignore these ports by default to avoid extra notifications
- port: 8983
  onOpen: ignore
- port: 7075
  onOpen: ignore
- port: 7000
  onOpen: ignore
- port: 3000
  onOpen: ignore
- port: 9292
  onOpen: ignore
tasks:
- name: Start App
  before: |
    # run chown because https://github.com/gitpod-io/gitpod/issues/4851
    sudo chown -R gitpod:999 /workspace/openlibrary
    # Give container (ie group) write access to this volume
    sudo chmod g+w -R /workspace/openlibrary/
    # because: https://github.com/gitpod-io/gitpod/issues/9311
    chmod o+rx /workspace/openlibrary
  # init runs once for each commit to the default branch
  init: ./scripts/setup_gitpod.sh
  env:
    OLCONF_COVERSTORE_PUBLIC_URL: "https://7075-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
  # command runs each time a user starts their workspace
  command: docker-compose up

github:
  prebuilds:
    # Disable all prebuilds ; it's not faster and often errors
    master: false
    pullRequests: false
    branches: false
    pullRequestsFromForks: false
