addons:
  apt:
    packages:
      - libgeoip-dev
matrix:
  include:
    - language: python
      - python: "2.7"
      - python: "3.6"
      - python: "3.7"
    dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
    allow_failures:
      - python: "3.6"
      - python: "3.7"
    - language: node_js
      - node_js: "9"
install:
  - pip install flake8
  - find . - name \*.py -exec flake8 {} +
  - make lint
  - pip install -r requirements_test.txt
  - npm install
script:
  - npm run lint
  - make test
