language: python
sudo: false
addons:
  apt:
    packages:
      - libgeoip-dev
python:
    - "2.7"
    - "3.6"
matrix:
  include:
    # https://docs.travis-ci.com/user/languages/javascript-with-nodejs
    - language: node_js
      node_js: "10"
      install: npm install -g eslint
      script: eslint
  allow_failures:
    - language: node_js
    - python: "3.6"
install:
  - pip install flake8
  - make lint
  - pip install -r requirements_test.txt
  - npm install
script: make test
