os: linux
dist: bionic
language: python
jobs:
  include:
    - name: “Python 2.7 on xenial”
      python: "2.7"
      dist: xenial
    - name: “Python 2.7 on bionic”
      python: "2.7"
    - name: “Python 3.8 make lint only”
      python: "3.8"
      install: pip install flake8
      script:
        - make lint
        # On pull requests, run all flake8 tests on modified code
        # Also test the entire files for syntax errors, undefined names, etc.
        # if clause avoids `fatal: ambiguous argument 'origin/master'` on git push
        - set -e
        - if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then
            git diff origin/master -U0 | flake8 --diff --max-line-length=88;
            echo "If the following test fails, please see PR-3040 for suggested fixes.";
            sleep 1;
            flake8 --select=F821 --show-source --statistics $(git diff origin/master --name-only | grep '.py' | tr '\n' ' ');
          fi
    - name: “Python 3.8 on bionic”
      python: "3.8"
  allow_failures:
    - name: “Python 3.8 on bionic”
install:
  - pip install flake8
  - make lint
  - pip install -r requirements_test.txt
  # if Travis is running Python 3, then
  #   refresh the git submodule ./vendor/infogami
  #   create a legacy Python for npm/node until nodejs/node#25789 is resolved
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.8" ]; then
      pushd vendor/infogami && git pull origin master && popd;
      pyenv install 2.7.14;
    fi
  - npm install
script:
  - make i18n
  - make test
