name: Bug Report
description:  Create a report to help us improve
labels: ["Type: Bug", "Needs: Triage", "Needs: Lead"]
body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT: Before posting, be sure to redact or remove sensitive data, such as passwords, secret keys, session cookies, etc.**
        Found a bug? Please fill out the sections below. 👍
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: Problem
      description: What problem are we solving? What does the experience look like today? What are the symptoms?
  - type: textarea
    attributes:
      label: Evidence / Screenshot
  - type: input
    attributes:
      label: Relevant URL
      description: Please provide the relevant URL.
      placeholder: "https://openlibrary.org/..."
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: What steps caused you to find the bug?
      placeholder: |
        1. Go to ...
        2. Do ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual
      description: What actually happened after these steps?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected
      description: What did you expect to happen?
    validations:
      required: true
  # - type: markdown
  #   attributes:
  #     value: |
  #       # Debugging Information
  # - type: dropdown
  #   attributes:
  #     label: Logged in?
  #     options:
  #       - "Yes"
  #       - "No"
  #   validations:
  #     required: true
  # - type: dropdown
  #   attributes:
  #     label: Browser?
  #     options:
  #       - "-"
  #       - Chrome
  #       - Firefox
  #       - Safari
  #       - Edge
  #       - Other
  #   validations:
  #     required: true
  # - type: dropdown
  #   attributes:
  #     label: Operating system?
  #     options:
  #       - "-"
  #       - Windows
  #       - macOS
  #       - Linux
  #       - iOS
  #       - Android
  #       - Other
  #   validations:
  #     required: true
  # - type: dropdown
  #   attributes:
  #     label: Environment?
  #     options:
  #       - prod
  #       - dev
  #       - local
  #   validations:
  #     required: true
  - type: textarea
    attributes:
      label: Context
      render: |
        - Browser (Chrome, Safari, Firefox, etc):
        - OS (Windows, Mac, etc):
        - Logged in (Y/N): Y
        - Environment (prod, dev, local): prod
  - type: markdown
    attributes:
      value: |
        # Next Steps
  - type: textarea
    attributes:
      label: Proposal & Constraints
      description: What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?
  - type: textarea
    attributes:
      label: Related files
      description: Files related to this issue; this is useful for new contributors who might want to help! If you're not sure, leave this blank; a maintainer will add them.
  - type: textarea # must be a textarea for tagging to work
    attributes:
      label: Stakeholders
      description: "@ tag stakeholders of this bug"
