version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.oldev
    image: oldev
    ports:
      - 8080:80
      - 7000:7000
    volumes:
      # Persistent volume mount for installed git submodules
      - ol-vendor:/openlibrary/vendor
      # Persistent volume mount for generated css and js
      - ol-build:/openlibrary/static/build
      # The above volume mounts are required so that the local dev bind mount below
      # does not clobber the data generated inside the image / container
      - ..:/openlibrary
#    depends_on:
#      - solr
    networks:
      - webnet
  solr:
    build:
      context: .
      dockerfile: ./Dockerfile.olsolr
    ports:
      - 8983:8080
    volumes:
      - solr-data:/var/lib/solr/data
    networks:
      - webnet
networks:
  webnet:
volumes:
  solr-data:
  ol-vendor:
  ol-build:
