version: '3.1'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    shm_size: "512M"
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: example
    working_dir: "/solr_builder"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - ".:/solr_builder"
    networks:
      - db-access

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8087:8080
    networks:
      - db-access

  solr:
    image: olsolr:latest
    restart: on-failure
    ports:
      - 8984:8080
    volumes:
      - solr-data:/var/lib/solr/data
    networks:
      - solr-access

  # On first launch need to create a core called "openlibrary" with our config & schema (one time only!)
  # docker-compose exec solr8 solr create -c openlibrary -d /opt/solr/server/solr/configsets/olconfig -n openlibrary
  solr8:
    image: solr:8
    restart: on-failure
    environment:
      # For historical compatibility with OL setup, but would be better to use default port
      - SOLR_PORT=8080
      # This is optimized for bulk loading, but should be shortened for production
      # and we should set autoSoftCommit to a value that makes sense for our query usage (5-15 sec?)
      - SOLR_OPTS=-Dsolr.autoCommit.maxTime=3600000 -Dsolr.autoSoftCommit.maxTime=3600000
      - SOLR_HEAP=1024m
    ports:
      - 8984:8080
    volumes:
      - solr8-data:/var/lib/solr/data/openlibrary
      - ../../conf/solr8-ol:/opt/solr/server/solr/configsets/olconfig:ro
    networks:
      - solr-access

  # Replica of production solr so we can get subjects
  solr-backup:
    image: olsolr:latest
    restart: on-failure
    ports:
      - 8985:8080
    volumes:
      #FIXME
      - /home/cdrini/solr-backup/data:/var/lib/solr/data
    networks:
      - solr-access

  # We need ability to use openlibrary code
  ol:
    image: olpython:latest
    # This build requires the olbase image to exist
    build:
      context: .
      dockerfile: Dockerfile.olpython
    working_dir: "/openlibrary/scripts/solr_builder"
    volumes:
      # Persistent volume mount for installed git submodules
      - ol-vendor:/openlibrary/vendor
      # The above volume mounts are required so that the local dev bind mount below
      # does not clobber the data generated inside the image / container
      - "../../:/openlibrary"
    networks:
      - solr-access
      - db-access

volumes:
  postgres-data:
  solr-data:
  solr8-data:
  ol-vendor:

networks:
  db-access:
  solr-access:
