version: '3.1'

services:
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: example
    working_dir: "/solr_builder"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - ".:/solr_builder"
    networks:
      - db-access

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8087:8080
    networks:
      - db-access

  solr:
    image: olsolr:latest
    restart: on-failure
    ports:
      - 8984:8080
    volumes:
      - solr-data:/var/lib/solr/data
    networks:
      - solr-access

  solr8:
    image: solr:8
    restart: on-failure
    environment:
      - SOLR_PORT=8080
      - SOLR_OPTS=-Dsolr.autoCommit.maxTime=3600000
    ports:
      - 8984:8080
    volumes:
      - solr8-data:/var/lib/solr/data/openlibrary
      - ../../conf/solr8-ol:/opt/solr/server/solr/configsets/olconfig:ro
    networks:
      - solr-access
    command: solr-precreate openlibrary /opt/solr/server/solr/configsets/olconfig

  # Replica of production solr so we can get subjects
  solr-backup:
    image: olsolr:latest
    restart: on-failure
    ports:
      - 8985:8080
    volumes:
      #FIXME
      - /home/cdrini/solr-backup/data:/var/lib/solr/data
    networks:
      - solr-access

  # We need ability to use openlibrary code
  ol:
    image: olpython:latest
    build:
      context: .
      dockerfile: Dockerfile.olpython
    working_dir: "/openlibrary/scripts/solr_builder"
    volumes:
      # Persistent volume mount for installed git submodules
      - ol-vendor:/openlibrary/vendor
      # The above volume mounts are required so that the local dev bind mount below
      # does not clobber the data generated inside the image / container
      - "../../:/openlibrary"
    networks:
      - solr-access
      - db-access

volumes:
  postgres-data:
  solr-data:
  solr8-data:
  ol-vendor:

networks:
  db-access:
  solr-access:
