name: codegen_api_docs
on: workflow_dispatch
permissions:
  contents: read

jobs:
  codegen_api_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          sudo apt-get update
          # https://lxml.de/installation.html#requirements
          sudo apt-get install libxml2-dev libxslt-dev
          pip install --upgrade pip setuptools wheel
          pip install "fastapi[all]" -r requirements_test.txt
          pip list --outdated
      - run: make git
      - run: mkdir main
      - run: touch main/__init__.py
      - run: python3 scripts/codegen_api_docs.py | tail -n +2 | tee main/app.py
      - name: generate openapi.json
        shell: python
        run: |
          import json  # https://github.com/tiangolo/fastapi/issues/1173
          import sys
          from fastapi.openapi.utils import get_openapi
          sys.path.insert(0, ".")  # Enable: from main import app
          from main import app
          app.title = "FastAPI shims for Open Library"
          with open("openapi.json", "w") as out_file:
              json.dump(app.get_openapi(
                  title=app.title,
                  version=getattr(app, "version", "0.0.2"),
                  openapi_version=getattr(app, "openapi_version", "0.0.2"),
                  description=getattr(app, "description", "description"),
                  routes=getattr(app, "routes", "routes"),
                  openapi_prefix=getattr(app, "openapi_prefix", "openapi_prefix")
              ), out_file)
      - run: cat openapi.json
